quarkus.application.name=kafka-throttling-system
quarkus.http.port=8080

# Kafka common
kafka.bootstrap.servers=localhost:9092

# Outgoing producer
mp.messaging.outgoing.messages-out.connector=smallrye-kafka
mp.messaging.outgoing.messages-out.topic=messages.in
mp.messaging.outgoing.messages-out.value.serializer=io.quarkus.kafka.client.serialization.ObjectMapperSerializer
mp.messaging.outgoing.messages-out.key.serializer=org.apache.kafka.common.serialization.StringSerializer
mp.messaging.outgoing.messages-out.acks=all
mp.messaging.outgoing.messages-out.retries=10

# Ingress
ingress.idempotency.ttl-seconds=86400
