quarkus.application.name=kafka-throttling-system
quarkus.http.port=8080

# Kafka common
kafka.bootstrap.servers=localhost:9092

# Outgoing producer
mp.messaging.outgoing.messages-out.connector=smallrye-kafka
mp.messaging.outgoing.messages-out.topic=messages.in
mp.messaging.outgoing.messages-out.value.serializer=io.quarkus.kafka.client.serialization.ObjectMapperSerializer
mp.messaging.outgoing.messages-out.key.serializer=org.apache.kafka.common.serialization.StringSerializer
mp.messaging.outgoing.messages-out.acks=all
mp.messaging.outgoing.messages-out.retries=10

# Ingress
ingress.idempotency.ttl-seconds=86400

# Throttling
throttle.capacity=100
throttle.refill-tokens=100
throttle.refill-period-ms=1000
throttle.bucket-key=global-throttle
throttle.acquire-timeout-ms=30000

throttle.redis.host=localhost
throttle.redis.port=6379

# Quarkus Redis client (idempotency store) — points to the same Redis instance
quarkus.redis.hosts=redis://localhost:6379

# DLQ outgoing
mp.messaging.outgoing.messages-dlq.connector=smallrye-kafka
mp.messaging.outgoing.messages-dlq.topic=messages.dlq
mp.messaging.outgoing.messages-dlq.value.serializer=io.quarkus.kafka.client.serialization.ObjectMapperSerializer
mp.messaging.outgoing.messages-dlq.key.serializer=org.apache.kafka.common.serialization.StringSerializer
mp.messaging.outgoing.messages-dlq.acks=all
mp.messaging.outgoing.messages-dlq.retries=10

# Incoming consumer
mp.messaging.incoming.messages-in.connector=smallrye-kafka
mp.messaging.incoming.messages-in.topic=messages.in
mp.messaging.incoming.messages-in.group.id=throttling-worker
mp.messaging.incoming.messages-in.value.deserializer=io.quarkus.kafka.client.serialization.ObjectMapperDeserializer
mp.messaging.incoming.messages-in.value.type=com.throttling.common.MessageEnvelope
mp.messaging.incoming.messages-in.key.deserializer=org.apache.kafka.common.serialization.StringDeserializer
mp.messaging.incoming.messages-in.failure-strategy=ignore
mp.messaging.incoming.messages-in.commit-strategy=throttled
mp.messaging.incoming.messages-in.auto.offset.reset=earliest
mp.messaging.incoming.messages-in.concurrency=1
mp.messaging.incoming.messages-in.fetch.max.wait.ms=500

consumer.max-hard-retries=5

admin.token=${ADMIN_TOKEN:dev-admin}

# Legacy REST client
quarkus.rest-client.legacy-api.url=http://localhost:8089
quarkus.rest-client.legacy-api.scope=jakarta.inject.Singleton
quarkus.rest-client.legacy-api.connect-timeout=2000
quarkus.rest-client.legacy-api.read-timeout=5000
